package com.projects.servicebroker.model;

import lombok.Data;
import net.bytebuddy.utility.RandomString;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

import javax.persistence.*;
import java.util.List;

@Data
@Entity
public class ServiceOffering {
    private String name;
    @Id //TODO maybe autogenerated?
    private String id;
    private String description;
    /*
    @ElementCollection
    private List<String> tags;
    @ElementCollection //TODO maybe rename table with @CollectionTable
    private List<String> requires;

     */
    private boolean bindable;
    /*
    private boolean instances_retrievable;
    private boolean bindings_retrievable;
    private boolean allow_context_updates;
    // private Object metadata; //TODO: Make this an object abiding the recommendation of https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata
    @OneToOne
    @Cascade(CascadeType.ALL)
    private DashboardClient dashboard_client;
    private boolean plan_updateable;

     */
    @OneToMany
    @Cascade(CascadeType.ALL)
    private List<ServicePlan> plans;

    public ServiceOffering() {
        id = RandomString.make();
    }
}
